version: '3.8'

services:
  server:
    build: .
    image: registry.aboyobam.me/weblab-server
    ports:
      - "127.0.0.1:5000:3000"
    depends_on:
      - db
  
  db:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
